In [30]:
# Performance Optimisation in Pynbody. Good for large arrarys. 
# Actual simulations

import numpy as np

import pynbody

a = np.zeros(10)

b = a[3:5]

%time b[1] = 100

a

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 11 µs


array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

In [31]:
c = a[[4,5,6]]

%time c[1] = 200

a

CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 8.82 µs


array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

In [32]:
d = pynbody.array.IndexedSimArray(a,[4,5,6,7])

%time d[1] = 200

a

CPU times: user 11 µs, sys: 1 µs, total: 12 µs
Wall time: 13.8 µs


array([  0.,   0.,   0.,   0., 100., 200.,   0.,   0.,   0.,   0.])

In [10]:
%time for i in range(10000) : d+=1

CPU times: user 97.8 ms, sys: 3.57 ms, total: 101 ms
Wall time: 100 ms


In [13]:
%time for i in range(900000) : a+=1

CPU times: user 1.23 s, sys: 8.19 ms, total: 1.24 s
Wall time: 1.25 s


In [15]:
# creating new test snapshot 
f = pynbody.new(dm=100)

sub_f = f[[20,21,22]]

In [16]:
sub_mass = sub_f['mass']

In [17]:
type(sub_mass)

pynbody.array.IndexedSimArray

In [18]:
sub_mass[:]=3

In [19]:
f['mass'][[20,21,22]]

SimArray([3., 3., 3.])

In [23]:
# Configuring Pynbody

pynbody.path

AttributeError: module 'pynbody' has no attribute 'path'

In [25]:
# What configuration does the group use?

pynbody.config

{'verbose': False,
 'centering-scheme': 'ssc',
 'snap-class-priority': [pynbody.snapshot.ramses.RamsesSnap,
  pynbody.snapshot.grafic.GrafICSnap,
  pynbody.snapshot.nchilada.NchiladaSnap,
  pynbody.snapshot.gadget.GadgetSnap,
  pynbody.snapshot.gadgethdf.EagleLikeHDFSnap,
  pynbody.snapshot.gadgethdf.GadgetHDFSnap,
  pynbody.snapshot.gadgethdf.SubFindHDFSnap,
  pynbody.snapshot.tipsy.TipsySnap,
  pynbody.snapshot.ascii.AsciiSnap],
 'halo-class-priority': [pynbody.halo.GrpCatalogue,
  pynbody.halo.AmigaGrpCatalogue,
  pynbody.halo.legacy.RockstarIntermediateCatalogue,
  pynbody.halo.rockstar.RockstarCatalogue,
  pynbody.halo.ahf.AHFCatalogue,
  pynbody.halo.subfind.SubfindCatalogue,
  pynbody.halo.hop.HOPCatalogue,
  pynbody.halo.adaptahop.NewAdaptaHOPCatalogue,
  pynbody.halo.adaptahop.AdaptaHOPCatalogue],
 'default-cosmology': {'a': 1.0,
  'h': 0.6777,
  'ns': 0.96,
  'running': 0.0,
  'omegaL0': 0.691,
  'omegaM0': 0.309,
  'omegaB0': 0.0482,
  'sigma8': 0.8288},
 'sph': {'smooth-par

In [33]:
# Understanding threading
pynbody.config['number_of_threads']



8

In [34]:
pynbody.openmp.get_cpus()

1